version: 1
services:
  - type: web
    name: server-ATC
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://jacobndiaye0113:RJinY2LalwMWEI1D@aton-tech-asra.k0s97.mongodb.net/?retryWrites=true&w=majority&appName=ATON-TECH-ASRA
      - key: PORT
        value: 5000
    autoDeploy: true